### ISSUE TITLE
Suggestion - common mod config screen

### ISSUE THREAD

**Issue by ManlyMarco** [bbepis/BepisPlugins#19]
Currently almost all mods use some random key to activate their UI. This is a mess, especially when you forget about said mod.

I've been thinking about making a plugin that shows additional setting screen for all installed mods. It would have a simple API to register plugins to it. Ideally plugins would use the API, but I believe it would be possible to check loaded plugins and either check for properties and fields, or dynamically decompile it's methods and look for keycode scans and show these (and allow you to press a button to emit this keycode as a convenience).

Any thoughts? Would this be a good part of these plugins, or as a stand-alone plugin?

**Comment by ezdiy** [comment]
The il decompiling is too fragile, but virtually all plugins do GetKeyState in Update().

When "show me hotkeys", erm, hotkey, is activated, then you're about to show the window - at that point hook GKS with harmony and record caller stack for each invocation you see for GKS. Pull in `  System.Diagnostics.StackFrame
` one level up from the hook, and you you'll get MethodBase and in assembly name of the caller.

That way you can present a simple list of DLL -> what keys it is looking for.

From there you can also "press" hotkeys, when user clicks at the detected pairing.

It is important to unhook after closing the hotkey peek dialog. Stack trace gazing in Update is very expensive and would drop FPS if done permanently.

The API and stuff, I'm afraid its too late for that.

**Comment by denikson** [comment]
@ezdiy By default, Harmony is not capable of hooking `Input.GetKeyString` or any other `extern` methods marked with `InternalCall`; see pardeike/Harmony#75. 

Even if you could do that, consider the following example

```csharp
if(Input.GetKey(KeyCode.LeftAlt) && Input.GetKey(KeyCode.M))
    // Pressing key combination Alt + M
```

The key combination will not be caught because of short-circuiting; the user would have to press <kbd>Alt</kbd> + <kbd>M</kbd> at least once for it to show up in the GUI. And that sounds a bit tedious (but that is my opinion; your mileage might wary).

@ManlyMarco I daresay that the idea is not bad. I'd say it's not too late, since there are not a whole lot of plug-ins available at the moment. Moreover, since all our plug-ins here are open source, adding support for key configuration would be quite trivial.

All in all, it's the plug-in dev's job anyway to allow to configure buttons even through a configuration file. Having minimalistic API for that would at least incentivise other developers to follow suit with providing easily configurable buttons.

**Comment by ManlyMarco** [comment]
Good idea about hooking with Harmony, didn't think of that. It will simplify a lot of things. Of course I will be careful with performance.

API - I know it's too late, but I think all it will be is public properties with some attributes. Easy to integrate, and at least I will be using it.

**Comment by ezdiy** [comment]
@denikson Aww, that sucks.

Both GetKey() and GetKeyDown() are hookable unless inlined. Both will also show up in the stack trace, but indeed it's up to the user to interpret that (smashing keyboard at random).

**Comment by ManlyMarco** [comment]
The thing's done and shipped.
