### ISSUE TITLE
Easy tutorial please 

### ISSUE THREAD

**Issue by kerotorres** [bbepis/BepisPlugins#45]
The English patch doesn't seem to work for my computer. Is it because it's a window 10? It keeps giving me an error and ultimately ends up translating nothing. I also don't understand how to start it up in the first place, I'm completely new and every video tutorial doesn't show how to set it up. they pretty much assume that everyone already has everything they need to download and already know coding. I'm really very confused and a step by step video tutorial would be really great please. 
thank you for taking your time to read this.

**Comment by DarkPulse** [comment]
Windows 10 shouldn't matter. This could be due to the translation format change. A new Plugins release should come in the next few days, which will update the format.

If you'd rather not wait, and don't mind working with WIP builds of BepinEx or the Plugins, you can obtain them from the Bleeding Edge site: [BepisPlugins](http://bepisbuilds.dyn.mk/bepis_plugins) and [BepInEx](http://bepisbuilds.dyn.mk/bepinex_be). If you download a Bleeding Edge BepinEx, you'll only need the x64 build for Koikatsu - x32 is for 32-bit Unity games (which doesn't include Koikatsu).

Due to the changes in translation format, you'll probably also want [the latest translations I've got on my fork.](https://github.com/bbepis/KoikatsuTranslation/tree/darkpulse-tl) These get updated from time to time, as my time permits. This will use the updated Translation format.

**Comment by kerotorres** [comment]
thank you so much for the info, it was very helpful! I'll try what you said and hope for the best ^w^
