### ISSUE TITLE
SliderUnlocker breaking voices of existing characters

### ISSUE THREAD

**Issue by izgtbvdb** [bbepis/BepisPlugins#72]
After installing the latest version, I notice some of my characters' voices were ridiculously low. Checking them in the character editor some of them were set to the minimum pitch (-300).

Temporarily removing SliderUnlocker.dll set them back to a minimum of 0 and made them sound normal again.

I'm guessing most of them were originally set to 0, which was previously the minimum and sounds much more natural.

Below is what I believe was the original pitch, and what it got replaced with. From what I can tell it is only affecting characters who were originally pitch 0, but what they end up as varies:

0 > -265
27 > 27
0 > 1
0 > -90
0 > -300
0 > -73
0 > -106
35 > 35
0 > 49

**Comment by DeathWeasel1337** [comment]
SliderUnlocker does what it says on the tin: unlocks sliders. It saves no extra data to cards or makes any special modifications to characters in any way. Previous versions of SliderUnlocker allowed you to set values outside of the normal 0-100 range, but the game did nothing special to handle such cases. -300 was effectively the same as 0. In BepisPlugins r10, some code was added to modify the voice pitch outside of the normal range instead of doing nothing so the expanded voice slider can function properly.

It's possible that you or the makers of the cards you're using set the voice pitch to negative values when negative values were functionally identical to 0. Unfortunately, as SliderUnlocker saves no data, it's impossible to tell when a card was made and whether it's intentional for the voice pitch to be at that particular value.

**Comment by izgtbvdb** [comment]
> Previous versions of SliderUnlocker allowed you to set values outside of the normal 0-100 range, but the game did nothing special to handle such cases.

Was this ever possible with voice pitch? I just replaced the current version of SliderUnlocker with the one included in r9, and the minimum pitch I could use was 0.

I don't understand how the cards could have ended up with negative pitch if I had no way of setting it in the negative in the first place?

As a test I made some cards with voice pitch 0 using SliderUnlocker r9, and then loaded them again with r10, and they were still set to 0 correctly, so I'm pretty stumped here.

**Comment by ManlyMarco** [comment]
I believe in either r8 or r9 sliders got changed so voice pitch wasn't unlocked, but it was unlocked in previous versions. Cards made back then can have the pitch unlocked but it didn't work until now.

It's not really a bug and there's no way to figure out if the pitch was changed in new or old version so this won't get fixed.
